Fix asgiref conflict
Fix for the following dependency error:
```
ERROR: Cannot install -r requirements.txt (line 10) and asgiref==3.2.7 because these package versions have conflict
ing dependencies.
```

The conflict is caused by:
    The user requested asgiref==3.2.7
    django 3.1.13 depends on asgiref<4 and >=3.2.10